name: Cancel old pull request workflows

on:
  workflow_run:
    workflows: ["PR build check"]
    types:
      - requested

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.10.0
      with:
        all_but_latest: true
        workflow_id: ${{ github.event.workflow.id }}
