# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [issues, pull_request]

jobs:
  label:'{"Auto Re-Open","Bot Update","Auto Updated":["Renovate updates"],"Bot Update":["WhiteSource Renovate"],"question":["help"]}'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
    - uses: actions/labeler@v4.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
